### ISSUE TITLE
 SAM Crashes when you Open Settings

### ISSUE THREAD

**Issue by lulacoding** [rex706/SAM#122] opened 2021-03-08 00:02 UTC
I found a bug when you open settings SAM Crashes, I'm not sure if it is due to something on My end but I'll leave a Clip attached for you to See.
https://streamable.com/0q3u3e

Hope this Help, Lula

**Comment by rex706** [comment] 2021-03-25 13:08
Where do you have SAM installed? Do you have .NET 4.8? Have you tried running as Admin? I cannot reproduce this issue people seem to be having with the settings causing a crash. You could try deleting SAMSetrtings.ini and it will make a fresh one for you.

**Comment by catgirlkara** [comment] 2021-08-21 17:55
Might be fixed by #135

**Comment by rex706** [comment] 2022-12-13 23:32
@lulacoding please let me know if this is still an issue with the latest release and what the error message in the popup is.

**Closed** 2023-06-30 22:25 UTC
Labels: bug
