### ISSUE TITLE
Crashes with saved accounts

### ISSUE THREAD

**Issue by notFunnys** [rex706/SAM#121] opened 2021-02-23 09:38 UTC
SAM is saving my account but if i close the window i cant open it again (crash)
[NET 4.8](https://i.imgur.com/KhUh8BP.png)

Translated: .NET Framework 4.8 or a newer update is already installed on this computer.

**Comment by rex706** [comment] 2021-02-26 16:00
Depending on where you have SAM installed, you may need to run it as Administrator. Reading/writing your data and settings files does not work in places like the Programs Folders without elevated privileges.

**Comment by rex706** [comment] 2021-03-25 13:09
Is this still a problem? I am unable to reproduce this issue and therefor cannot make a fix for it.

**Comment by catgirlkara** [comment] 2021-08-21 17:52
duplicates #109

**Comment by catgirlkara** [comment] 2021-08-21 17:56
Fixed in #135

**Closed** 2022-10-10 16:41 UTC
