### ISSUE TITLE
1.2.3.0 2accoutns with 2fa, makes SAM freeze and messes up input of 2fa

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#15] opened 2019-02-19 01:06 UTC
Having 2 accounts added, then clicking login on one of them makes the app freeze, followed by a crash or freezes such long enough it gives error at 2fa input screen.

**Comment by rex706** [comment] 2019-02-19 01:21
SAM will wait for the 2FA window to show before continuing execution if a shared secret is configured for the account. Are you clicking on anything else while waiting for SAM to log you in after selecting an account? This shouldn't matter, though, as it will focus the 2FA window after the code is generated.

**Comment by wazerstar** [comment] 2019-02-19 01:50
No it tries actually to inject before and says that the it was invalid in steam, I do not touch anything, if anything its because of the freeze in the app of SAM.

**Comment by rex706** [comment] 2019-02-19 01:55
Very weird. I have multiple accounts with 2FA active working fine. 

You configured the shared secrets for the respective accounts, correct?

Add me on Discord so we can discuss your issues more easily: rex706#6521

**Comment by rex706** [comment] 2019-02-19 06:22
I think I now understand what you mean. Sorry for not understanding at first.

Apparently the 2FA does not work the second time a 2FA account is used with the same instance of SAM running. I have replicated this problem and will come up with a fix for it soon.

In the mean time, though, you should be able to just close and reopen SAM to log into the other account you need.

**Comment by wazerstar** [comment] 2019-02-19 11:16
Here's what I did as of with 1.2.3.1.

I was already logged in by manual.

I have 2 accounts added with 2fa and steam profiles.

I click on the second added account, it logs in fine.

Then I try to test account "first being added"

it logs into steam and still gives the 2fa error where SAM freezes.

I then do what you told me to do, shut down SAM and try opening the account again, but SAM closes instantly just as before.

**Comment by wazerstar** [comment] 2019-02-19 11:54
Not sure if you closes steam properly, but steam actually allows command line to be executed for shutdown.

Think that would much more safe to use and also make sure steam shuts down properly, and then check if all its processes are closes or not.

ie.
steamwebhelper.exe
steam.exe
SteamService.exe

cmd
steam.exe -shutdown

**Comment by gmmanonymus111** [comment] 2019-02-19 15:26
@rex706 @wazerstar I think the problem is that SAM tries to enter the 2fa code before the steam prompt loads properly. I encountered this problem after modifying the code to type user/pass (instead of -login parameter) to make steam save the password.
SAM missed the first 4 characters of my usernames there, after adding a 5-second delay, it worked. I think 500-1000 ms should be enough for 2fa popup.
Or we need an other reliable way to check if steam's prompt loaded completely.

**Comment by wazerstar** [comment] 2019-02-19 16:23
> 
> 
> @rex706 @wazerstar I think the problem is that SAM tries to enter the 2fa code before the steam prompt loads properly. I encountered this problem after modifying the code to type user/pass (instead of -login parameter) to make steam save the password.
> SAM missed the first 4 characters of my usernames there, after adding a 5-second delay, it worked. I think 500-1000 ms should be enough for 2fa popup.
> Or we need an other reliable way to check if steam's prompt loaded completely.

Can just read titles of windows, and only paste if active window is active and if not wait for it.

Yeah would like that option too, to enter username/password too to make save account until next restart of steam.

**Comment by rex706** [comment] 2019-02-19 17:07
@gmmanonymus111 @wazerstar My original approach with SAM was to do what you suggest and enter the login fields manually somehow in order to get Steam to remember the last logged in account, but I ran into exactly what you're describing with the window not being fully initialized. I hesitate to just go the *easy* route with timers, but that may still not handle every situation correctly if a user has a terribly slow PC and leaving users with too much time between actions probably isn't the right way to do it either. 

I'm at work at the moment, but when I get home later today I will take another stab at coming up with a good way to make sure the windows are loaded fully before trying to enter any information. I will also consider making Steam shut down properly using the command instead of trying to end the task directly as this could be causing problems as you said.

I very much appreciate you both helping me out with this.

**Comment by wazerstar** [comment] 2019-02-19 21:32
> 
> 
> @gmmanonymus111 @wazerstar My original approach with SAM was to do what you suggest and enter the login fields manually somehow in order to get Steam to remember the last logged in account, but I ran into exactly what you're describing with the window not being fully initialized. I hesitate to just go the _easy_ route with timers as that may still not handle every situation correctly if a user has a terribly slow PC and leaving users with too much time between actions probably isn't the right way to do it either.
> 
> I'm at work at the moment, but when I get home later today I will take another stab at coming up with a good way to make sure the windows are loaded fully before trying to enter any information. I will also consider making Steam shut down properly using the command instead of trying to end the task directly as this could be causing problems as you said.
> 
> I very much appreciate you both helping me out with this.

sounds good, just remember to make a second check when doing steam.exe -shutdown, If i remember correctly you cannot shutdown steam while a game is open hence it will say a game is still running, please exit before closing steam,

**Comment by rex706** [comment] 2019-02-21 00:01
@wazerstar @gmmanonymus111 I think I have figured out a nice way to wait for the Steam Guard window to be fully initialized and ready for input. I decided to go back and see if I can get this to work when logging in too, but the problem then becomes the previously logged in user already occupying the 'Account name' field, which makes the input cursor start on the password field. I am not sure if there is a way to tell if the 'Account name' field is actually occupied without checking the process memory, which I hesitate to want to do with something like Steam. The Shift+Tab combo will bring the cursor up to the 'Account name' field if it starts on 'Password', but again there doesn't seem to be a nice way to know that is where it started. I am also now using the -shutdown command so hopefully that process will go more smoothly. 

I'll push a commit soon so you can see what I'm talking about.

**Comment by wazerstar** [comment] 2019-02-21 00:44
> 
> 
> @wazerstar @gmmanonymus111 I think I have figured out a nice way to wait for the Steam Guard window to be fully initialized and ready for input. I decided to go back and see if I can get this to work when logging in too, but the problem then becomes the previously logged in user already occupying the 'Account name' field, which makes the input cursor start on the password field. I am not sure if there is a way to tell if the 'Account name' field is actually occupied without checking the process memory, which I hesitate to want to do with something like Steam. The Shift+Tab combo will bring the cursor up to the 'Account name' field if it starts on 'Password', but again there doesn't seem to be a nice way to know that is where it started. I am also now using the -shutdown command so hopefully that process will go more smoothly.
> 
> I'll push a commit soon so you can see what I'm talking about.

Will u compile > release too? :D

**Comment by rex706** [comment] 2019-02-21 00:57
@wazerstar I will definitely make another release after I run some more tests on a few more *slower* devices and confirm what I came up with works. 

Maybe @gmmanonymus111 can test it out too and see if they can get logged in consistently?

**Comment by gmmanonymus111** [comment] 2019-02-21 05:37
Sure, I'll run some test, but I can do that only tomorrow.
For the login username issue, I faced the same, my solution was to click on
the username field, press Ctrl-a (this selects all text, or does nothing
depending on the contents of this field), then start typing. This solution
needs relative coordinates, so it should always work off the user has the
default steam skin (I also led to test with different resolutions, but I
think it should workthat way too)

Alec <notifications@github.com> ezt írta (időpont: 2019. febr. 21., Cs
1:57):

**Comment by gmmanonymus111** [comment] 2019-02-22 13:16
@rex706 I finally got time to test it, but sadly it doesn't work as it should be. First login is ok, then the second/third etc will hang because of a wrong auth code (SAM detects the popup, but for some reason, it types instantly, like `WaitForInputIdle` wasn't even there. I'm not sure about slow PCs, though.

**Comment by rex706** [comment] 2019-02-22 14:30
@gmmanonymus111 Yeah I was having the same issue unfortunately. The first login attempt works fine, but every time after that without restarting SAM does not work as if it completely ignores the wait function like you said. 

I will check out your pull request and see if that solves the problem!

**Comment by rex706** [comment] 2019-02-22 22:24
It auto closed the issue when I merged the code. 

@gmmanonymus111 Frustratingly, this doesn't seem to work for me every time. The super weird part is that even though I can clearly see SAM typing in the code well after the window has been fully loaded, it still gives me the `Sorry that wasn't quite right` error, but not always. 

Now I'm waiting how ever long Steam makes you wait for too many incorrect log in attempts. 

Maybe the codes it is entering have expired at the last second? But that wouldn't make sense since it generates a completely fresh one only a few seconds later to still fail. 

I really can't figure out why it would work every time the first try, but not any other attempt after until SAM is restarted. This makes me think some memory isn't being freed correctly, but most, if not all, variables used in that process are generated fresh anyway. Restarting SAM every login is an option, but that feels hacky.

I'll just have to take more time troubleshooting this.

**Comment by wazerstar** [comment] 2019-02-22 23:06
A steam guard code takes very long time to expire even after it has already been renewed by another code, you can check for your self, copy one and wait a few minutes, it will still work :)

**Comment by rex706** [comment] 2019-02-23 01:35
@gmmanonymus111 Oddly enough, using the regular `GenerateSteamGuardCode()` instead of the one that uses a time input fixes the problem I was having with the incorrect codes. It works every time I have tested without fail so far. Is there a specific reason you decided to use this one over the default one?

I'm still trying to figure out how to fix the problem of not waiting for the 2FA window unless SAM is reset. It literally waits fine every time if restarted, so it has to be something in the code.

**Comment by gmmanonymus111** [comment] 2019-02-23 09:23
@rex706 Well, I tought it would be a good idea to sync with steam's time before generating a code to avoid problems in case something with local time is not right but if the generation works (even better) without steam time, I won't complain.

**Closed** 2019-02-23 22:35 UTC
